CREATE TABLE IF NOT EXISTS caddy_availability (
  id bigint generated by default as identity primary key,
  caddy_email text not null,
  date date not null,
  is_available boolean not null default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  UNIQUE(caddy_email, date)
);
