# Cloudflare Pages Configuration
name = "golf-caddy"
compatibility_date = "2024-01-01"

# Pages用の設定
pages_build_output_dir = "."

# 自動デプロイ設定
[env.production]
name = "golf-caddy"
compatibility_date = "2024-01-01"

# 環境変数（実際の値はCloudflare Pages設定画面で入力）
[env.production.vars]
NODE_VERSION = "18"

# Secrets（実際の値はCloudflare Pages設定画面で設定）
# 以下の環境変数をCloudflare Pages設定画面で設定してください：
# 1. LINE_CHANNEL_ACCESS_TOKEN: LINE Developers Consoleで取得したChannel Access Token
# 2. LINE_CHANNEL_SECRET: LINE Developers Consoleで取得したChannel Secret
# 3. SUPABASE_URL: SupabaseプロジェクトのURL
# 4. SUPABASE_SERVICE_KEY: Supabaseのservice_role key（RLSをバイパス）

# 必要な環境変数一覧：
# 1. LINE_CHANNEL_ACCESS_TOKEN: LINE Developers Consoleで取得
# 2. LINE_CHANNEL_SECRET: LINE Developers Consoleで取得  
# 3. SUPABASE_URL: SupabaseプロジェクトのURL
# 4. SUPABASE_SERVICE_KEY: Supabaseのservice_role key（RLSをバイパス）
# 5. RESEND_API_KEY: ResendのAPIキー（メール送信用）
